#!/usr/bin/env bash
# shellcheck shell=bash
# ---------------------------------------------------------------------------------------------- #
# Directory Explorer: Adds directory stacking, ls after cd, and fuzzy finding behavior to cd.    #
#                                                                                                #
# MIT License                                                                                    #
# Copyright © 2026 Josh Beale                                                                    #
# Permission is hereby granted, free of charge, to any person obtaining a copy                   #
# of this software and associated documentation files (the "Software"), to deal                  #
# in the Software without restriction, including without limitation the rights                   #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell                      #
# copies of the Software, and to permit persons to whom the Software is                          #
# furnished to do so, subject to the following conditions:                                       #
#                                                                                                #
# The above copyright notice and this permission notice shall be included in all                 #
# copies or substantial portions of the Software.                                                #
#                                                                                                #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR                     #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,                       #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE                    #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER                         #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,                  #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE                  #
# SOFTWARE.                                                                                      #
# ---------------------------------------------------------------------------------------------- #

# ---------------------------- #
# User Configuration Variables #
# ---------------------------- #

declare _de_USER_DIRSTACK="$HOME/.dirstack"
declare -i _de_STACK_DISPLAY_LIMIT="5"
declare _de_LS_AFTER_CD=true
declare _de_FUZZY_SEARCH_WHEN_BLANK=true

# --------------------- #
# End of user variables #
# --------------------- #

function _de_usage() {
  cat <<EOF
Adds directory stacking, ls after cd, and fuzzy finding behavior to cd.

Usage: $(basename "$0") [-L/-P [-e]] [-h] [-v] [-l] [-s[=][DIRECTORY]/-p[=][0-9]+] [PATH]

Options:
	-h, --help			Show this help message and exit.
	    --version			Show version information and exit.
	-l, --list-directories		List the current directory stack.
	-s, --stack-directory		Add the current directory to the top of the directory stack.
	-p, --pop-directory		Pop the specified directory from the directory stack and change to it.
	    --purge-directory-stack		Empty the current directory stack.
  -L			Resolve symlinks during traversal after processing .. in path (Default Behavior).
	-P			Prevents following symlinks after processing .. in path.
	-e			Return a non-zero status if working directory resolution fails with -P enabled.
EOF
}

function _de_version() {
  cat <<EOF
Directory Explorer 0.1.0
Copyright © 2026 Josh Beale <jbeale2023@gmail.com>.
Licence MIT: <https://directory.fsf.org/wiki/License:Expat>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
EOF
}

# If there are directories on the stack, list them, one per line, with added line numbers.
# If there are more than $_de_STACK_DISPLAY_LIMIT directories in the stack, truncate the output.
function _de_list-directories() {
  if [ -f "${_de_USER_DIRSTACK:-$HOME/.dirstack}" ]; then
    declare -i STACK_SIZE
    STACK_SIZE=$(wc -l "${_de_USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
    [ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 0; }
    echo "There are currently $STACK_SIZE directories on the stack."
    tac "${_de_USER_DIRSTACK:-$HOME/.dirstack}" | head -n "${_de_STACK_DISPLAY_LIMIT:-5}" | cat -n
  else
    echo "The directory stack is empty." && return 0
  fi
}

# Add a directory to the stack.
# Defaults to $PWD if no directory is provided.
function _de_stack-directory() {
  realpath "${1:-"$PWD"}" >>"${_de_USER_DIRSTACK:-$HOME/.dirstack}"
  echo "Added ${1:-"$PWD"} to the stack."
  declare -i STACK_SIZE
  STACK_SIZE=$(wc -l "${_de_USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
  (("STACK_SIZE" == 1)) && { echo "There is currently 1 directory on the stack." && return 0; }
  echo "There are currently $STACK_SIZE directories on the stack." && return 0
}

# If there is a directory on top of the stack, pop it and change to it.
# Optionally, instead select the directory specified by user numerical input.
function _de_pop-directory() {
  if [[ $1 =~ [0-9]+ ]]; then
    declare -ir DIRNUM="$1"
  else
    declare -ir DIRNUM="1"
  fi
  if [ -f "${_de_USER_DIRSTACK:-$HOME/.dirstack}" ]; then
    declare -i STACK_SIZE
    STACK_SIZE=$(wc -l "${_de_USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
    [ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 1; }
    [ "$DIRNUM" -gt "$STACK_SIZE" ] && { echo "Invalid stack index $DIRNUM" && return 1; }
    local STACK_TOP
    STACK_TOP=$(sed -i -e "$DIRNUM w /dev/stdout" -e "$DIRNUM d" "${_de_USER_DIRSTACK:-$HOME/.dirstack}")
    cdopts+=("$STACK_TOP") &&
      echo "Popped $STACK_TOP from the stack." && {
      if (("$STACK_SIZE" >= 3)); then
        echo "There are currently $((--STACK_SIZE)) directories on the stack."
      elif [[ "$STACK_SIZE" == 2 ]]; then
        echo "There is currently $((--STACK_SIZE)) directory on the stack."
      else
        echo "The directory stack is empty."
      fi
      _de_directory-explorer
    } || return 1
  else
    { echo "The directory stack is empty." && return 1; }
  fi
}

# If there are directories on the stack, empty it.
function _de_purge-directory-stack() {
  if [ -f "${_de_USER_DIRSTACK:-$HOME/.dirstack}" ]; then
    declare -i STACK_SIZE
    STACK_SIZE=$(wc -l "${_de_USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
    [ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 0; }
    echo "Purging $STACK_SIZE directories from the stack."
    rm "${_de_USER_DIRSTACK:-$HOME/.dirstack}"
  fi
}

# Main function for changing to a given target path.
# If $_de_FUZZY_SEARCH_WHEN_BLANK is enabled, launches fzf with tree preview if no path is provided.
function _de_directory-explorer() {
  declare -r TARGET_PATH="${cdopts[${#cdopts[@]} - 1]}"
  if [ "$TARGET_PATH" == "--" ]; then
    if [ "${_de_FUZZY_SEARCH_WHEN_BLANK:-true}" ]; then
      local DIR
      DIR=$(find / -type d 2>/dev/null | fzf --preview 'tree {}')
      if [ -n "$DIR" ]; then
        cdopts+=("$DIR")
      fi
    else
      cdopts+=("$HOME")
    fi
  fi
  if [ "$TARGET_PATH" != "--" ]; then
    [ -f "$TARGET_PATH" ] && { echo "$TARGET_PATH is a file." && return 1; }
  fi
  builtin cd "${cdopts[@]}" || return 1
  [ "$_de_LS_AFTER_CD" ] && ls
}

# vim: set filetype=bash:
