#!/usr/bin/env bash
# shellcheck shell=bash
# ---------------------------------------------------------------------------------------------- #
# Directory Explorer: Adds directory stacking, ls after cd, and fuzzy finding behavior to cd.    #
#                                                                                                #
# MIT License                                                                                    #
# Copyright © 2026 Josh Beale                                                                    #
# Permission is hereby granted, free of charge, to any person obtaining a copy                   #
# of this software and associated documentation files (the "Software"), to deal                  #
# in the Software without restriction, including without limitation the rights                   #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell                      #
# copies of the Software, and to permit persons to whom the Software is                          #
# furnished to do so, subject to the following conditions:                                       #
#                                                                                                #
# The above copyright notice and this permission notice shall be included in all                 #
# copies or substantial portions of the Software.                                                #
#                                                                                                #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR                     #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,                       #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE                    #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER                         #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,                  #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE                  #
# SOFTWARE.                                                                                      #
# ---------------------------------------------------------------------------------------------- #

function usage() {
	cat <<EOF
Adds directory stacking, ls after cd, and fuzzy finding behavior to CD.

Usage: $(basename "$0") [-L/-P] [-h] [-v] [-l] [-s[=][DIRECTORY]/-p[=][0-9]+]

Options:
	-h, --help			Show this help message and exit.
	    --version			Show version information and exit.
	-l, --list-directories		List the current directory stack.
	-s, --stack-directory		Add the current directory to the top of the directory stack.
	-p, --pop-directory		Pop the specified directory from the directory stack and change to it.
	    --purge-directory-stack		Empty the current directory stack.
  -L			Resolve symlinks during traversal after processing .. in path (Default Behavior).
	-P			Prevents following symlinks after processing .. in path.
	-e			Return a non-zero status if working directory resolution fails with -P enabled.
EOF
}

function version() {
	cat <<EOF
Directory Explorer 0.1.0
Copyright © 2026 Josh Beale <jbeale2023@gmail.com>.
Licence MIT: <https://directory.fsf.org/wiki/License:Expat>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
EOF
}

# If there are directories on the stack, list them, one per line, with added line numbers.
# If there are more than $STACK_DISPLAY_LIMIT directories in the stack, truncate the output.
function list-directories() {
	if [ -f "${USER_DIRSTACK:-$HOME/.dirstack}" ]; then
		declare -i STACK_SIZE
		STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
		[ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 0; }
		echo "There are currently $STACK_SIZE directories on the stack."
		tac "${USER_DIRSTACK:-$HOME/.dirstack}" | head -n "${STACK_DISPLAY_LIMIT:-5}" | cat -n
	else
		echo "The directory stack is empty." && return 0
	fi
}

# Add a directory to the stack.
# Defaults to $PWD if no directory is provided.
function stack-directory() {
	if [ "$#" -eq 0 ]; then
		realpath "$PWD" >>"${USER_DIRSTACK:-$HOME/.dirstack}"
	else
		realpath "$1" >>"${USER_DIRSTACK:-$HOME/.dirstack}"
	fi
	declare -i STACK_SIZE
	STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
	(("STACK_SIZE" == 1)) && { echo "There is currently 1 directory on the stack." && return 0; }
	echo "There are currently $STACK_SIZE directories on the stack." && return 0
}

# vim: set filetype=bash:
